remote_theme: pmarsceill/just-the-docs
title: Plerion RPG
color_scheme: plerion

# Define Jekyll collections
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  build:
    permalink: "/:collection/:path/"
    output: true
  pages:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    build:
      # Give the collection a name
      name: Build
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: true
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: true
    pages:
      name: Pages
